---
title: "R Notebook"
output: html_notebook
---

```{r}
library(SeuratData)
library(scone)
library(Seurat)
library(ggplot2)
library(RColorBrewer)
InstallData('pbmcsca')
data('pbmcsca')
```

```{r}
```

```{r}
# cc <- c(brewer.pal(9, "Set1"))
# batch = factor(pbmcsca$Method)
# qc = pbmcsca$nUMI
# qc <- sapply(qc, as.numeric)
# o = order(qc)[order(batch[order(qc)])]
# barplot(qc[o], col=cc[batch][o], 
#         border=cc[batch][o], main="UMI counts")
# legend("bottomleft", legend=levels(batch), fill=cc,cex=0.4)
# ```
# ```{r}
# expr <- GetAssayData(pbmcsca)
# # experiment_name <- '10x Chromium (v2)'
# # col_select <- pbmcsca$Method == experiment_name
# # col_select_1 <- pbmcsca$Experiment == 'pbmc2'
# # expr = expr[, col_select]
# # expr <- expr[which(apply(expr > 0, 1, any)), ]
# # pbmcsca_small <- pbmcsca[, (pbmcsca$Method == experiment_name)]
```

```{r}
data(housekeeping)
hk = intersect(housekeeping$V1,rownames(pbmcsca))

# Mean log10(x+1) expression
# Assumed False Negatives
```


```{r}
# num_reads = quantile(expr[expr > 0])[4]
# num_cells = 0.25*ncol(expr)
# is_common = rowSums(expr >= num_reads ) >= num_cells

# Metric-based Filtering
# mfilt = metric_sample_filter(as.matrix(expr),
#                             gene_filter = is_common,
#                             pos_controls = rownames(expr) %in% hk,
#                             zcut = 3, mixture = FALSE,
#                             plot = TRUE)
```

```{r}
#mfilt = !apply(simplify2array(mfilt[!is.na(mfilt)]),1,any)
#goodDat = expr[, mfilt]
# data <- subset(pbmcsca, idents='pbmc1')
expr = GetAssayData(pbmcsca)
n=1000
sampled = sample(colnames(expr), size=n, replace=F)
expr = expr[, sampled]
data = pbmcsca[, sampled]
print(dim(data))
expr = expr[which(apply(expr > 0, 1, any)), ]
goodDat = as.matrix(expr)
qc_metrics = c('nCount_RNA', 'nFeature_RNA', 'nGene', 'nUMI', 'percent.mito')
qc = as.matrix(data[[qc_metrics]])
qc = apply(qc, 2, as.numeric)
ppq = scale(qc[,apply(qc,2,sd) > 0],center = TRUE,scale = TRUE)
negcon = intersect(rownames(goodDat),hk)
memory.limit()
memory.limit(size=56000)
```

```{r}
my_scone <- SconeExperiment(goodDat,
                            qc=ppq,
                            bio=as.factor(data$CellType),
                            batch=as.factor(data$Method),
                            negcon_ruv=rownames(goodDat) %in% negcon,
                            )
```

```{r}
EFF_FN = function (ei)
{
  sums = colSums(ei > 0)
  eo = t(t(ei)*sums/mean(sums))
  return(eo)
}

## ----- Scaling Argument -----

scaling=list(none=identity, # Identity - do nothing

             eff = EFF_FN, # User-defined function

             sum = SUM_FN, # SCONE library wrappers...
             tmm = TMM_FN, 
             uq = UQ_FN,
             fq = FQT_FN,
             deseq = DESEQ_FN)
```

```{r}
# my_scone <- scone(my_scone,
#                 scaling=scaling,
#                 k_qc=3, k_ruv = 0,
#                 adjust_bio="no",
#                 run=FALSE)

```

```{r}
BiocParallel::register(
  BiocParallel::SerialParam()
) # Register BiocParallel Serial Execution
rm(data)
rm(expr)
rm(goodDat)
rm(pbmcsca)
gc()

my_scone <- scone(my_scone,
                  scaling=scaling,
                  run=TRUE,
                  # k_ruv=0,
                  eval_kclust = 2:6,
                  stratified_pam = FALSE,
                  return_norm = "in_memory",
                  zero = "postadjust")
```
```{r}
pc_obj = prcomp(apply(t(get_scores(my_scone)),1,rank),
                center = TRUE,scale = FALSE)
bp_obj = biplot_color(pc_obj,y = -get_score_ranks(my_scone),expand = .6)
```

```{r}
bp_obj = biplot_color(pc_obj,y = -get_score_ranks(my_scone),expand = .6)

points(t(bp_obj[1,]), pch = 1, col = "red", cex = 1)
points(t(bp_obj[1,]), pch = 1, col = "red", cex = 1.5)

points(t(bp_obj[rownames(bp_obj) == "none,none,no_uv,no_bio,no_batch",]),
       pch = 1, col = "blue", cex = 1)
points(t(bp_obj[rownames(bp_obj) == "none,none,no_uv,no_bio,no_batch",]),
       pch = 1, col = "blue", cex = 1.5)

arrows(bp_obj[rownames(bp_obj) == "none,none,no_uv,no_bio,no_batch",][1],
       bp_obj[rownames(bp_obj) == "none,none,no_uv,no_bio,no_batch",][2],
       bp_obj[1,][1],
       bp_obj[1,][2],
       lty = 2, lwd = 2)
```
```{r}
# saveRDS(my_scone, file='n_2000_scone.rds')
saveRDS(my_scone, file='n_1000_scone.rds')
```